"""add table 'files'

Revision ID: f262dded28ba
Revises: 5c5f53b2c7f6
Create Date: 2023-08-21 15:32:41.812040

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f262dded28ba'
down_revision = '5c5f53b2c7f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
                    sa.Column('files_id', sa.Integer(), nullable=False),
                    sa.Column('file_name', sa.String(length=100), nullable=False),
                    sa.Column('columns', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('files_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
